//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracerHub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TracerHub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{clientIP}&apos; connected to &apos;{group}&apos;.
        /// </summary>
        internal static string Trace_Connected {
            get {
                return ResourceManager.GetString("Trace_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{clientIP}&apos; disconnected from &apos;{group}&apos;.
        /// </summary>
        internal static string Trace_Disconnected {
            get {
                return ResourceManager.GetString("Trace_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP &apos;{clientIP}&apos; attempted to connect to tracer hub without specifying a groupName..
        /// </summary>
        internal static string Trace_NoGroupName {
            get {
                return ResourceManager.GetString("Trace_NoGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{clientIP}&apos; reconnected to &apos;{group}&apos;.
        /// </summary>
        internal static string Trace_Reconnected {
            get {
                return ResourceManager.GetString("Trace_Reconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTraceLevel(&quot;{source}&quot;, {level}).
        /// </summary>
        internal static string Trace_SetTraceLevel {
            get {
                return ResourceManager.GetString("Trace_SetTraceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraceEvent(&quot;{source}&quot;, {level}, &quot;[...]&quot;).
        /// </summary>
        internal static string Trace_TraceEvent {
            get {
                return ResourceManager.GetString("Trace_TraceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query string value &apos;groupName&apos; must be specified..
        /// </summary>
        internal static string TracerHub_GroupNameRequired {
            get {
                return ResourceManager.GetString("TracerHub_GroupNameRequired", resourceCulture);
            }
        }
    }
}
