//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace TracerHub.Properties
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class Strings
	{
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class TracerHub
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Query string value 'groupName' must be specified.
			/// </summary>
			public static string GroupNameRequired { get { return Resources.TracerHub_GroupNameRequired; } }
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Trace
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	'{clientIP}' connected to '{group}'
			/// </summary>
			public static string Connected(object clientIP, object group)
			{
				return Resources.Trace_Connected.FormatWith(new 
				{
					clientIP = clientIP,
					group = group,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	'{clientIP}' disconnected from '{group}'
			/// </summary>
			public static string Disconnected(object clientIP, object group)
			{
				return Resources.Trace_Disconnected.FormatWith(new 
				{
					clientIP = clientIP,
					group = group,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	IP '{clientIP}' attempted to connect to tracer hub without specifying a groupName.
			/// </summary>
			public static string NoGroupName(object clientIP)
			{
				return Resources.Trace_NoGroupName.FormatWith(new 
				{
					clientIP = clientIP,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	'{clientIP}' reconnected to '{group}'
			/// </summary>
			public static string Reconnected(object clientIP, object group)
			{
				return Resources.Trace_Reconnected.FormatWith(new 
				{
					clientIP = clientIP,
					group = group,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	SetTraceLevel("{source}", {level})
			/// </summary>
			public static string SetTraceLevel(object source, object level)
			{
				return Resources.Trace_SetTraceLevel.FormatWith(new 
				{
					source = source,
					level = level,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	{level}:{source}:{message}
			/// </summary>
			public static string TraceEvent(object level, object source, object message)
			{
				return Resources.Trace_TraceEvent.FormatWith(new 
				{
					level = level,
					source = source,
					message = message,
				});
			}
		}
	}
}

